### PR TITLE
Builders- Sport, BigHorn, and LoneStar

### PR DESCRIPTION
**Pull request by Catyell2**
It is still a WIP but made the pull anyway.

### CODE REVIEW

**Comment by anthonykulis** [comment]
thats good to make a pr right away. as you complete reviewable code you will then merge that into *your* master and this will update. thats why commit messages are important since it allows your team leader to know what you did and what they are looking at

**Comment by Catyell2** [comment]
@nourelhoda89 I know I said I would have this done by yesterday but tonight has been my first chance to sit down and write anything since Friday morning. I will get this one mostly done before the end of tonight. I am running into some issues with using the cab we selected in the `askForColorAndInterior` but you should be too `this.body =  new CrewCab(new Quarterpanels(paint,null),new EngineCompartment(new Hood(paint, null)), new TruckCabin(seat), cabAndBox);` only makes CrewCabs regardless of choice.

**Comment by Catyell2** [comment]
Accidently added BigHorn in this pull.

**Comment by Catyell2** [comment]
@nourelhoda89 
For some reason I can't make a new branch to make a pull request off.  SO `LoneStarBuilder` has been added by accident to this pull request. I will keep trying to get the new branch to work for the EC one but I will try to rename the pull and that is all 3 in this one.

**Comment by anthonykulis** [comment]
Do not worry. It's a bit late in the game to try and master what you can
with git. Nour, just keep the PR open as he completes his parts

**Comment by nourelhoda89** [comment]
Ok !

**Comment by Catyell2** [comment]
It should be ready to merge if you approve.

**Pull request merged**
