### PR TITLE
SportDriveLine

### PR DESCRIPTION
**Pull request by Calvarez14**
SportDriveLine is completed and tested.

### CODE REVIEW

**Comment by anthonykulis** [comment]
Needs UML

**Comment by Calvarez14** [comment]
sportdriveline - page 1
This is my UML for part of my project.

**Comment by Calvarez14** [comment]
@nourelhoda89 I'm all done and ready to merge in. @anthonykulis I'm all done with the side of my project.

**Comment by ClarkLindsay** [comment]
@Calvarez14 @nourelhoda89 Fixed the constructors to not pass null.

**Pull request merged**
